name: meme_portfolio
description: "Ghassan's Portfolio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.0.dev <4.0.0'

dependencies:
  just_audio: ^0.9.36
  flutter:
    sdk: flutter
  gradient_borders: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/meme.jpg
    - assets/audio/lb.mp3